language: python

sudo: false

python:
  - "2.7"
  - "3.4"

addons:
  apt:
    packages:
      - gdal-bin
      - libgdal-dev
      - libgdal1h
      - libgdal1-dev
      - libgeos-dev

install:
  - pip install pip --upgrade
  - pip install .
  - pip install -r requirements-gdal.txt
  - pip install coveralls

script:
  - python -m unittest tests
  - coverage run --source=pywps -m unittest tests

after_success:
  - coveralls

# whitelist
branches:
  only:
    - master
