language: python
python:
  - "2.7"
  - "3.4"

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-gdal
  - sudo apt-get install -qq python3-gdal
  - "pip install . --use-mirrors"
  - "pip install owslib --use-mirrors"

script: "python tests/__init__.py"
