language: python
python:
  - "2.7"
  - "3.4"

# Handle git submodules yourself
git:
    submodules: false

# Use system wide packages, needed for gdal
virtualenv:
  system_site_packages: true

install:
  - sudo apt-get update -qq
  - sudo apt-get install python-gdal python3-gdal
  - "pip install ."

script: "python tests/__init__.py"
