language: python

sudo: false

python:
  - "2.7"
  - "3.4"

addons:
  apt:
    packages:
      - gdal-bin
      - libgdal-dev
      - libgdal1h
      - libgdal1-dev
      - libgeos-dev

# Handle Git submodules yourself
git:
    submodules: false

install:
  - pip install pip --upgrade
  - pip install .
  - pip install -r requirements-gdal.txt

script: "python -m unittest tests"

# whitelist
branches:
  only:
    - master
